package de.persosim.simulator.protocols.pace;

import java.math.BigInteger;
import java.security.InvalidAlgorithmParameterException;
import java.security.KeyPair;
import java.security.NoSuchAlgorithmException;
import java.security.NoSuchProviderException;
import java.security.PrivateKey;
import java.security.PublicKey;
import java.security.SecureRandom;
import java.security.spec.InvalidKeySpecException;

import de.persosim.simulator.crypto.CryptoUtil;
import de.persosim.simulator.crypto.DomainParameterSet;

/**
 * This class performs the generic, i.e. non key agreement specific parts of generic mapping.
 * 
 * @author slutters
 *
 */
public abstract class GenericMapping implements Mapping {
	
	@Override
	public MappingResult performMapping(DomainParameterSet domainParametersUnmapped, byte[] sNonce, byte[] publicKeyComponentPcd) throws NoSuchAlgorithmException, NoSuchProviderException, InvalidAlgorithmParameterException, InvalidKeySpecException {
		KeyPair keyPairPiccUnmapped = CryptoUtil.generateKeyPair(domainParametersUnmapped, new SecureRandom());
		PublicKey publicKeyPcdUnMapped = domainParametersUnmapped.reconstructPublicKey(publicKeyComponentPcd);
		
		byte[] secretPointOfKeyAgreementEncoding = performKeyAgreement(domainParametersUnmapped, keyPairPiccUnmapped.getPrivate(), publicKeyPcdUnMapped);
		
		BigInteger sNonceBigInt = new BigInteger(1, sNonce);
		DomainParameterSet domainParametersMapped = performGenericMappingOfDomainParameters(domainParametersUnmapped, sNonceBigInt, secretPointOfKeyAgreementEncoding);
		
		KeyPair keyPairPiccMapped = CryptoUtil.updateKeyPairToNewDomainParameters(keyPairPiccUnmapped, domainParametersMapped);
		
		byte[] mappingResponse = domainParametersUnmapped.encodePublicKey(keyPairPiccUnmapped.getPublic());
		
		return new MappingResult(domainParametersMapped, keyPairPiccMapped, mappingResponse);
	}
	
	/**
	 * This method performs the generic mapping of domain parameters.
	 * The common secret as generated by the key agreement must be encoded as follows.
	 * In case of DH: unsigned byte array representation of a {@link BigInteger}
	 * In case of ECDH: encoding according to ANSI X9.62
	 * i.e. "0x04|unsigned x-coordinate|unsigned y-coordinate" for uncompressed encoding
	 * 
	 * @param domainParameters the domain parameters
	 * @param sNonce the nonce s as generated by the PICC
	 * @param secretOfKeyAgreement the common secret as produced by the key agreement
	 * @return the mapped domain parameters
	 */
	//TODO SLS this method exists very similar in IntegratedMapping but was removed from Mapping. Why???
	//This is due to the differences between mapping functions and common secrets.
	//Parameters entering the mapping may in one mapping be used for computing the common secret while in
	//another mapping they directly become involved in the mapping function itself.
	//This nesting of parameters complicates a common approach.
	//Maybe sacrifice statelessness of mappings in favor of more straight forward usability?
	public abstract DomainParameterSet performGenericMappingOfDomainParameters(DomainParameterSet domainParameters, BigInteger sNonce, byte[] secretOfKeyAgreement);
	
	/**
	 * This method performs a key agreement specified by the implementing class.
	 * 
	 * @param domainParameters the common domain parameters used by the provided keys
	 * @param privKeyPicc the private key
	 * @param pubKeyPcd the public key
	 * @return the result of the key agreement
	 */
	public abstract byte[] performKeyAgreement(DomainParameterSet domainParameters, PrivateKey privKeyPicc, PublicKey pubKeyPcd);
	
	@Override
	public String getMappingName() {
		return "Generic Mapping";
	}
	
}
