//
//package de.persosim.simulator.control.soap.service;
//
//import java.net.MalformedURLException;
//import java.net.URL;
//import javax.xml.namespace.QName;
//import javax.xml.ws.Service;
//import javax.xml.ws.WebEndpoint;
//import javax.xml.ws.WebServiceClient;
//import javax.xml.ws.WebServiceException;
//import javax.xml.ws.WebServiceFeature;
//
//
///**
// * This class was generated by the JAX-WS RI.
// * JAX-WS RI 2.2.9-b130926.1035
// * Generated source version: 2.2
// *
// */
//@WebServiceClient(name = "PersoSimRemoteControlService", targetNamespace = "http://service.soap.control.simulator.persosim.de/", wsdlLocation = "http://localhost:8888/persosim/PersoSimRemoteControl?wsdl")
//public class PersoSimRemoteControlService2
//    extends Service
//{
//
//    private final static URL PERSOSIMREMOTECONTROLSERVICE_WSDL_LOCATION;
//    private final static WebServiceException PERSOSIMREMOTECONTROLSERVICE_EXCEPTION;
//    private final static QName PERSOSIMREMOTECONTROLSERVICE_QNAME = new QName("http://service.soap.control.simulator.persosim.de/", "PersoSimRemoteControlService");
//
//    static {
//        URL url = null;
//        WebServiceException e = null;
//        try {
//            url = new URL("http://localhost:8888/persosim/PersoSimRemoteControl?wsdl");
//        } catch (MalformedURLException ex) {
//            e = new WebServiceException(ex);
//        }
//        PERSOSIMREMOTECONTROLSERVICE_WSDL_LOCATION = url;
//        PERSOSIMREMOTECONTROLSERVICE_EXCEPTION = e;
//    }
//
//    public PersoSimRemoteControlService2() {
//        super(__getWsdlLocation(), PERSOSIMREMOTECONTROLSERVICE_QNAME);
//    }
//
//    public PersoSimRemoteControlService2(WebServiceFeature... features) {
//        super(__getWsdlLocation(), PERSOSIMREMOTECONTROLSERVICE_QNAME, features);
//    }
//
//    public PersoSimRemoteControlService2(URL wsdlLocation) {
//        super(wsdlLocation, PERSOSIMREMOTECONTROLSERVICE_QNAME);
//    }
//
//    public PersoSimRemoteControlService2(URL wsdlLocation, WebServiceFeature... features) {
//        super(wsdlLocation, PERSOSIMREMOTECONTROLSERVICE_QNAME, features);
//    }
//
//    public PersoSimRemoteControlService2(URL wsdlLocation, QName serviceName) {
//        super(wsdlLocation, serviceName);
//    }
//
//    public PersoSimRemoteControlService2(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
//        super(wsdlLocation, serviceName, features);
//    }
//
//    /**
//     *
//     * @return
//     *     returns PersoSimRemoteControl
//     */
//    @WebEndpoint(name = "PersoSimRemoteControlPort")
//    public PersoSimRemoteControlInterface getPersoSimRemoteControlPort() {
//        return super.getPort(new QName("http://service.soap.control.simulator.persosim.de/", "PersoSimRemoteControlPort"), PersoSimRemoteControlInterface.class);
//    }
//
//    /**
//     *
//     * @param features
//     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
//     * @return
//     *     returns PersoSimRemoteControl
//     */
//    @WebEndpoint(name = "PersoSimRemoteControlPort")
//    public PersoSimRemoteControlInterface getPersoSimRemoteControlPort(WebServiceFeature... features) {
//        return super.getPort(new QName("http://service.soap.control.simulator.persosim.de/", "PersoSimRemoteControlPort"), PersoSimRemoteControlInterface.class, features);
//    }
//
//    private static URL __getWsdlLocation() {
//        if (PERSOSIMREMOTECONTROLSERVICE_EXCEPTION!= null) {
//            throw PERSOSIMREMOTECONTROLSERVICE_EXCEPTION;
//        }
//        return PERSOSIMREMOTECONTROLSERVICE_WSDL_LOCATION;
//    }
//
//}
