//
//package de.persosim.simulator.control.soap.service;
//
//import javax.jws.WebMethod;
//import javax.jws.WebParam;
//import javax.jws.WebResult;
//import javax.jws.WebService;
//import javax.jws.soap.SOAPBinding;
//import javax.xml.ws.Action;
//
//
///**
// * This class was generated by the JAX-WS RI.
// * JAX-WS RI 2.2.9-b130926.1035
// * Generated source version: 2.2
// *
// */
//@WebService(name = "PersoSimRemoteControl", targetNamespace = "http://service.soap.control.simulator.persosim.de/")
//@SOAPBinding(style = SOAPBinding.Style.RPC)
//public interface PersoSimRemoteControlInterface2 {
//
//
//    /**
//     *
//     * @return
//     *     returns java.lang.String
//     */
//    @WebMethod
//    @WebResult(partName = "return")
//    @Action(input = "http://service.soap.control.simulator.persosim.de/PersoSimRemoteControl/resetRequest", output = "http://service.soap.control.simulator.persosim.de/PersoSimRemoteControl/resetResponse")
//    public String reset();
//
//    /**
//     *
//     * @param arg0
//     * @return
//     *     returns java.lang.Object
//     */
//    @WebMethod
//    @WebResult(partName = "return")
//    @Action(input = "http://service.soap.control.simulator.persosim.de/PersoSimRemoteControl/getAdapterRequest", output = "http://service.soap.control.simulator.persosim.de/PersoSimRemoteControl/getAdapterResponse")
//    public Object getAdapter(
//        @WebParam(name = "arg0", partName = "arg0")
//        String arg0);
//
//    /**
//     *
//     * @param arg0
//     * @return
//     *     returns java.lang.String
//     */
//    @WebMethod
//    @WebResult(partName = "return")
//    @Action(input = "http://service.soap.control.simulator.persosim.de/PersoSimRemoteControl/loadPersoRequest", output = "http://service.soap.control.simulator.persosim.de/PersoSimRemoteControl/loadPersoResponse")
//    public String loadPerso(
//        @WebParam(name = "arg0", partName = "arg0")
//        String arg0);
//
//    /**
//     *
//     * @param arg0
//     * @return
//     *     returns java.lang.String
//     */
//    @WebMethod
//    @WebResult(partName = "return")
//    @Action(input = "http://service.soap.control.simulator.persosim.de/PersoSimRemoteControl/sendApduRequest", output = "http://service.soap.control.simulator.persosim.de/PersoSimRemoteControl/sendApduResponse")
//    public String sendApdu(
//        @WebParam(name = "arg0", partName = "arg0")
//        String arg0);
//
//    /**
//     *
//     * @return
//     *     returns java.lang.String
//     */
//    @WebMethod
//    @WebResult(partName = "return")
//    @Action(input = "http://service.soap.control.simulator.persosim.de/PersoSimRemoteControl/getIdentifierRequest", output = "http://service.soap.control.simulator.persosim.de/PersoSimRemoteControl/getIdentifierResponse")
//    public String getIdentifier();
//
//}
